### ISSUE TITLE
RFC: including selenium jar? 

### ISSUE THREAD

**Issue by scott2449** [dowjones/fiveby#13]
I want it to be easy to start fiveby (and not have to spin up a selenium server separately) but that comes at the cost of having to download the fairly large selenium jar.. maybe we should include a command that will install the jar, check for java, etc.. then in code we can just check for the file as well. And of course none if this is an issue when the dev provides a url.

**Comment by m1sta** [comment]
+1

**Comment by scott2449** [comment]
npm post install script should be enough
