### ISSUE TITLE
How can I connect to SauceLabs using the fiveby-config.json file?

### ISSUE THREAD

**Issue by aasimsyed** [dowjones/fiveby#19]
I am trying to config fiveby to use with SauceLabs, but am not having a lot of success. I’m a bit green, so was wondering if you could point me in the right direction to get me past this. 

I tried to use this for the value of hubUrl in my config file, but was getting authentication errors:
“hubUrl”: “http://SAUCE_USERNAME:SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub”,

If I use SauceConnect and add a gulp task to start SC, then set hubUrl to “http://127.0.0.1:4445”, then I don’t get authentication errors, but the tests fail (the slush generated tests) with error:
“TypeError: undefined is not a function”

What is the proper way to configure this (ideally without having to use SauceConnect)?

**Comment by scott2449** [comment]
Is the site you are testing internet facing? Also can SC on "your" box connect to google and bootstrap website?

**Comment by scott2449** [comment]
Also http://stackoverflow.com/questions/21170734/how-can-i-use-selenium-webdriver-package-with-saucelabs

meaning:

``` javascript
{
"hubUrl": "http://ondemand.saucelabs.com:80/wd/hub",
  "browsers": {
    "chrome": {
      "username": process.env.SAUCE_USERNAME,
      "accessKey": process.env.SAUCE_ACCESS_KEY
    },
    //...
  },
//...
```

**Comment by scott2449** [comment]
I am assuming this worked out.
