### ISSUE TITLE
Nemo evaluation

### ISSUE THREAD

**Issue by grawk** [dowjones/fiveby#9]
Hi @scott2449 I just watched your presentation at Node Summit. You and I have spent the last few months working on similar products (see: http://nemojs.com)! Given your experience, I'd love to get your feedback on Nemo. If you want to ping me today and meet in person (I'll introduce myself if I see you around), please do! @mattedelman / @nemojs_news (Twitter)

**Comment by grawk** [comment]
Feel free to close this and provide feedback some other way if you'd like. I was hoping to catch you in person. Not trying to pollute your issues list.

**Comment by scott2449** [comment]
No problem at all! I took a look and it seems we were thinking along very similar lines and that our approach is better then most IMO :smile: Sorry we didn't get to chat at the conference.

There are definitely some key differences, but you are right in that here is probably not the best venue for that discussion. We can use chat or even setup of a call if you'd like to talk about how we got here and were we are going with our respective libs.
